// Code generated by onit-generate. DO NOT EDIT.

package apps

import (
	appsv1 "github.com/onosproject/onos-test/pkg/helm/api/apps/v1"
	appsv1beta1 "github.com/onosproject/onos-test/pkg/helm/api/apps/v1beta1"
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
)

type Client interface {
	V1() appsv1.Client
	V1beta1() appsv1beta1.Client
}

func NewClient(resources resource.Client, filter resource.Filter) Client {
	return &client{
		Client: resources,
		filter: filter,
	}
}

type client struct {
	resource.Client
	filter resource.Filter
}

func (c *client) V1() appsv1.Client {
	return appsv1.NewClient(c.Client, c.filter)
}

func (c *client) V1beta1() appsv1beta1.Client {
	return appsv1beta1.NewClient(c.Client, c.filter)
}
