// Code generated by onit-generate. DO NOT EDIT.

package v1

import (
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"time"
)

var RoleKind = resource.Kind{
	Group:   "rbac.authorization.k8s.io",
	Version: "v1",
	Kind:    "Role",
	Scoped:  true,
}

var RoleResource = resource.Type{
	Kind: RoleKind,
	Name: "roles",
}

func NewRole(role *rbacv1.Role, client resource.Client) *Role {
	return &Role{
		Resource: resource.NewResource(role.ObjectMeta, RoleKind, client),
		Object:   role,
	}
}

type Role struct {
	*resource.Resource
	Object *rbacv1.Role
}

func (r *Role) Delete() error {
	return r.Clientset().
		RbacV1().
		RESTClient().
		Delete().
		NamespaceIfScoped(r.Namespace, RoleKind.Scoped).
		Resource(RoleResource.Name).
		Name(r.Name).
		VersionedParams(&metav1.DeleteOptions{}, metav1.ParameterCodec).
		Timeout(time.Minute).
		Do().
		Error()
}
