// Code generated by onit-generate. DO NOT EDIT.

package networking

import (
	networkingv1beta1 "github.com/onosproject/onos-test/pkg/helm/api/networking/v1beta1"
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
)

type Client interface {
	V1beta1() networkingv1beta1.Client
}

func NewClient(resources resource.Client, filter resource.Filter) Client {
	return &client{
		Client: resources,
		filter: filter,
	}
}

type client struct {
	resource.Client
	filter resource.Filter
}

func (c *client) V1beta1() networkingv1beta1.Client {
	return networkingv1beta1.NewClient(c.Client, c.filter)
}
