// Code generated by onit-generate. DO NOT EDIT.

package batch

import (
	batchv1 "github.com/onosproject/onos-test/pkg/helm/api/batch/v1"
	batchv1beta1 "github.com/onosproject/onos-test/pkg/helm/api/batch/v1beta1"
	batchv2alpha1 "github.com/onosproject/onos-test/pkg/helm/api/batch/v2alpha1"
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
)

type Client interface {
	V1() batchv1.Client
	V1beta1() batchv1beta1.Client
	V2alpha1() batchv2alpha1.Client
}

func NewClient(resources resource.Client, filter resource.Filter) Client {
	return &client{
		Client: resources,
		filter: filter,
	}
}

type client struct {
	resource.Client
	filter resource.Filter
}

func (c *client) V1() batchv1.Client {
	return batchv1.NewClient(c.Client, c.filter)
}

func (c *client) V1beta1() batchv1beta1.Client {
	return batchv1beta1.NewClient(c.Client, c.filter)
}

func (c *client) V2alpha1() batchv2alpha1.Client {
	return batchv2alpha1.NewClient(c.Client, c.filter)
}
