// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: simulation/simulation.proto

package simulation

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	model "model"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SimulationLifecycleRequest is a simulation request
type SimulationLifecycleRequest struct {
	// simulation is the simulation name
	Simulation string `protobuf:"bytes,1,opt,name=simulation,proto3" json:"simulation,omitempty"`
	// args is the simulation arguments
	Args map[string]string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *SimulationLifecycleRequest) Reset()         { *m = SimulationLifecycleRequest{} }
func (m *SimulationLifecycleRequest) String() string { return proto.CompactTextString(m) }
func (*SimulationLifecycleRequest) ProtoMessage()    {}
func (*SimulationLifecycleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{0}
}
func (m *SimulationLifecycleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimulationLifecycleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimulationLifecycleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SimulationLifecycleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulationLifecycleRequest.Merge(m, src)
}
func (m *SimulationLifecycleRequest) XXX_Size() int {
	return m.Size()
}
func (m *SimulationLifecycleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulationLifecycleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimulationLifecycleRequest proto.InternalMessageInfo

func (m *SimulationLifecycleRequest) GetSimulation() string {
	if m != nil {
		return m.Simulation
	}
	return ""
}

func (m *SimulationLifecycleRequest) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

// SimulationLifecycleResponse is a response to a SimulationRequest
type SimulationLifecycleResponse struct {
}

func (m *SimulationLifecycleResponse) Reset()         { *m = SimulationLifecycleResponse{} }
func (m *SimulationLifecycleResponse) String() string { return proto.CompactTextString(m) }
func (*SimulationLifecycleResponse) ProtoMessage()    {}
func (*SimulationLifecycleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{1}
}
func (m *SimulationLifecycleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimulationLifecycleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimulationLifecycleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SimulationLifecycleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulationLifecycleResponse.Merge(m, src)
}
func (m *SimulationLifecycleResponse) XXX_Size() int {
	return m.Size()
}
func (m *SimulationLifecycleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulationLifecycleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimulationLifecycleResponse proto.InternalMessageInfo

// SimulateRequest is a request to run a simulation
type SimulateRequest struct {
	// simulation is the simulation name
	Simulation string `protobuf:"bytes,1,opt,name=simulation,proto3" json:"simulation,omitempty"`
	// method is the simulation method to run
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
}

func (m *SimulateRequest) Reset()         { *m = SimulateRequest{} }
func (m *SimulateRequest) String() string { return proto.CompactTextString(m) }
func (*SimulateRequest) ProtoMessage()    {}
func (*SimulateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{2}
}
func (m *SimulateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimulateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimulateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SimulateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulateRequest.Merge(m, src)
}
func (m *SimulateRequest) XXX_Size() int {
	return m.Size()
}
func (m *SimulateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimulateRequest proto.InternalMessageInfo

func (m *SimulateRequest) GetSimulation() string {
	if m != nil {
		return m.Simulation
	}
	return ""
}

func (m *SimulateRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

// SimulateResponse is a response indicating a simulation output
type SimulateResponse struct {
	// trace is a simulation trace
	Trace *model.Trace `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	// error is a simulation error
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *SimulateResponse) Reset()         { *m = SimulateResponse{} }
func (m *SimulateResponse) String() string { return proto.CompactTextString(m) }
func (*SimulateResponse) ProtoMessage()    {}
func (*SimulateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17e12b66aec6c312, []int{3}
}
func (m *SimulateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimulateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimulateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SimulateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulateResponse.Merge(m, src)
}
func (m *SimulateResponse) XXX_Size() int {
	return m.Size()
}
func (m *SimulateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimulateResponse proto.InternalMessageInfo

func (m *SimulateResponse) GetTrace() *model.Trace {
	if m != nil {
		return m.Trace
	}
	return nil
}

func (m *SimulateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*SimulationLifecycleRequest)(nil), "onos.test.simulation.SimulationLifecycleRequest")
	proto.RegisterMapType((map[string]string)(nil), "onos.test.simulation.SimulationLifecycleRequest.ArgsEntry")
	proto.RegisterType((*SimulationLifecycleResponse)(nil), "onos.test.simulation.SimulationLifecycleResponse")
	proto.RegisterType((*SimulateRequest)(nil), "onos.test.simulation.SimulateRequest")
	proto.RegisterType((*SimulateResponse)(nil), "onos.test.simulation.SimulateResponse")
}

func init() { proto.RegisterFile("simulation/simulation.proto", fileDescriptor_17e12b66aec6c312) }

var fileDescriptor_17e12b66aec6c312 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x4b, 0x8b, 0xda, 0x50,
	0x14, 0xc7, 0xbd, 0xbe, 0xa8, 0x47, 0xa8, 0x7a, 0x11, 0x09, 0x91, 0x06, 0x09, 0xb4, 0xb8, 0x28,
	0xd1, 0xda, 0x45, 0x8b, 0xbb, 0x96, 0x76, 0x51, 0x28, 0x5d, 0x44, 0xe9, 0xa6, 0xab, 0x34, 0x9e,
	0xc9, 0x84, 0x89, 0xb9, 0xce, 0xbd, 0x37, 0xce, 0xe4, 0x5b, 0xcc, 0x97, 0x1a, 0x98, 0xa5, 0x30,
	0x9b, 0x59, 0x0e, 0xfa, 0x45, 0x86, 0x3c, 0x4c, 0x64, 0x70, 0x1e, 0x6e, 0xdc, 0x84, 0xf3, 0xfc,
	0xfd, 0xf3, 0x3f, 0x84, 0x40, 0x57, 0xb8, 0xf3, 0xc0, 0xb3, 0xa4, 0xcb, 0xfc, 0x41, 0x1e, 0x1a,
	0x0b, 0xce, 0x24, 0xa3, 0x6d, 0xe6, 0x33, 0x61, 0x48, 0x14, 0xd2, 0xc8, 0x7b, 0x6a, 0xdb, 0x61,
	0x0e, 0x8b, 0x07, 0x06, 0x51, 0x94, 0xcc, 0xaa, 0xad, 0x39, 0x9b, 0xa1, 0x37, 0x88, 0x9f, 0x49,
	0x49, 0xbf, 0x26, 0xa0, 0x4e, 0xb2, 0xbd, 0xdf, 0xee, 0x09, 0xda, 0xa1, 0xed, 0xa1, 0x89, 0xe7,
	0x01, 0x0a, 0x49, 0x35, 0x80, 0x9c, 0xaa, 0x90, 0x1e, 0xe9, 0xd7, 0xcc, 0x9d, 0x0a, 0xfd, 0x03,
	0x65, 0x8b, 0x3b, 0x42, 0x29, 0xf6, 0x4a, 0xfd, 0xfa, 0x68, 0x6c, 0xec, 0x7b, 0x19, 0xe3, 0x69,
	0xbe, 0xf1, 0x8d, 0x3b, 0xe2, 0xa7, 0x2f, 0x79, 0x68, 0xc6, 0x1c, 0xf5, 0x0b, 0xd4, 0xb2, 0x12,
	0x6d, 0x42, 0xe9, 0x0c, 0xc3, 0x54, 0x35, 0x0a, 0x69, 0x1b, 0x2a, 0x4b, 0xcb, 0x0b, 0x50, 0x29,
	0xc6, 0xb5, 0x24, 0x19, 0x17, 0xbf, 0x12, 0xfd, 0x1d, 0x74, 0xf7, 0xca, 0x88, 0x05, 0xf3, 0x05,
	0xea, 0xbf, 0xa0, 0x91, 0xb6, 0x5f, 0x6d, 0xad, 0x03, 0xd5, 0x39, 0xca, 0x53, 0x36, 0x4b, 0xc5,
	0xd2, 0x4c, 0xff, 0x0b, 0xcd, 0x1c, 0x95, 0xe0, 0xe9, 0x47, 0xa8, 0x48, 0x6e, 0xd9, 0x18, 0x63,
	0xea, 0xa3, 0xce, 0xce, 0x1d, 0x92, 0x63, 0x4f, 0xa3, 0xae, 0x99, 0x0c, 0x45, 0x2e, 0x90, 0x73,
	0xc6, 0xb7, 0x2e, 0xe2, 0x64, 0x74, 0x5b, 0xce, 0xc0, 0x8c, 0x4f, 0x90, 0x2f, 0x5d, 0x1b, 0xe9,
	0x12, 0x1a, 0x13, 0x94, 0xc1, 0x22, 0xf7, 0x46, 0x87, 0x87, 0x1e, 0x59, 0xfd, 0x74, 0xc0, 0x46,
	0x6a, 0x28, 0x04, 0x3a, 0x45, 0x8b, 0xff, 0x60, 0x17, 0xfe, 0xb1, 0xa5, 0x03, 0x78, 0xbb, 0x6b,
	0x99, 0xf1, 0xe3, 0xc8, 0x5e, 0x42, 0xeb, 0x91, 0xe3, 0x63, 0x29, 0xff, 0x83, 0x37, 0xdb, 0x0f,
	0x8a, 0xbe, 0x7f, 0x76, 0x3d, 0x53, 0xf9, 0xf0, 0xd2, 0x58, 0x82, 0x1e, 0x92, 0xef, 0xca, 0xcd,
	0x5a, 0x23, 0xab, 0xb5, 0x46, 0xee, 0xd7, 0x1a, 0xb9, 0xda, 0x68, 0x85, 0xd5, 0x46, 0x2b, 0xdc,
	0x6d, 0xb4, 0xc2, 0xff, 0x6a, 0xfc, 0x03, 0xf8, 0xfc, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xbc,
	0x4c, 0xb6, 0x5e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SimulatorServiceClient is the client API for SimulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimulatorServiceClient interface {
	SetupSimulation(ctx context.Context, in *SimulationLifecycleRequest, opts ...grpc.CallOption) (*SimulationLifecycleResponse, error)
	TearDownSimulation(ctx context.Context, in *SimulationLifecycleRequest, opts ...grpc.CallOption) (*SimulationLifecycleResponse, error)
	SetupSimulator(ctx context.Context, in *SimulationLifecycleRequest, opts ...grpc.CallOption) (*SimulationLifecycleResponse, error)
	TearDownSimulator(ctx context.Context, in *SimulationLifecycleRequest, opts ...grpc.CallOption) (*SimulationLifecycleResponse, error)
	Simulate(ctx context.Context, in *SimulateRequest, opts ...grpc.CallOption) (SimulatorService_SimulateClient, error)
}

type simulatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewSimulatorServiceClient(cc *grpc.ClientConn) SimulatorServiceClient {
	return &simulatorServiceClient{cc}
}

func (c *simulatorServiceClient) SetupSimulation(ctx context.Context, in *SimulationLifecycleRequest, opts ...grpc.CallOption) (*SimulationLifecycleResponse, error) {
	out := new(SimulationLifecycleResponse)
	err := c.cc.Invoke(ctx, "/onos.test.simulation.SimulatorService/SetupSimulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) TearDownSimulation(ctx context.Context, in *SimulationLifecycleRequest, opts ...grpc.CallOption) (*SimulationLifecycleResponse, error) {
	out := new(SimulationLifecycleResponse)
	err := c.cc.Invoke(ctx, "/onos.test.simulation.SimulatorService/TearDownSimulation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) SetupSimulator(ctx context.Context, in *SimulationLifecycleRequest, opts ...grpc.CallOption) (*SimulationLifecycleResponse, error) {
	out := new(SimulationLifecycleResponse)
	err := c.cc.Invoke(ctx, "/onos.test.simulation.SimulatorService/SetupSimulator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) TearDownSimulator(ctx context.Context, in *SimulationLifecycleRequest, opts ...grpc.CallOption) (*SimulationLifecycleResponse, error) {
	out := new(SimulationLifecycleResponse)
	err := c.cc.Invoke(ctx, "/onos.test.simulation.SimulatorService/TearDownSimulator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) Simulate(ctx context.Context, in *SimulateRequest, opts ...grpc.CallOption) (SimulatorService_SimulateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SimulatorService_serviceDesc.Streams[0], "/onos.test.simulation.SimulatorService/Simulate", opts...)
	if err != nil {
		return nil, err
	}
	x := &simulatorServiceSimulateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SimulatorService_SimulateClient interface {
	Recv() (*SimulateResponse, error)
	grpc.ClientStream
}

type simulatorServiceSimulateClient struct {
	grpc.ClientStream
}

func (x *simulatorServiceSimulateClient) Recv() (*SimulateResponse, error) {
	m := new(SimulateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimulatorServiceServer is the server API for SimulatorService service.
type SimulatorServiceServer interface {
	SetupSimulation(context.Context, *SimulationLifecycleRequest) (*SimulationLifecycleResponse, error)
	TearDownSimulation(context.Context, *SimulationLifecycleRequest) (*SimulationLifecycleResponse, error)
	SetupSimulator(context.Context, *SimulationLifecycleRequest) (*SimulationLifecycleResponse, error)
	TearDownSimulator(context.Context, *SimulationLifecycleRequest) (*SimulationLifecycleResponse, error)
	Simulate(*SimulateRequest, SimulatorService_SimulateServer) error
}

// UnimplementedSimulatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSimulatorServiceServer struct {
}

func (*UnimplementedSimulatorServiceServer) SetupSimulation(ctx context.Context, req *SimulationLifecycleRequest) (*SimulationLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupSimulation not implemented")
}
func (*UnimplementedSimulatorServiceServer) TearDownSimulation(ctx context.Context, req *SimulationLifecycleRequest) (*SimulationLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TearDownSimulation not implemented")
}
func (*UnimplementedSimulatorServiceServer) SetupSimulator(ctx context.Context, req *SimulationLifecycleRequest) (*SimulationLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupSimulator not implemented")
}
func (*UnimplementedSimulatorServiceServer) TearDownSimulator(ctx context.Context, req *SimulationLifecycleRequest) (*SimulationLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TearDownSimulator not implemented")
}
func (*UnimplementedSimulatorServiceServer) Simulate(req *SimulateRequest, srv SimulatorService_SimulateServer) error {
	return status.Errorf(codes.Unimplemented, "method Simulate not implemented")
}

func RegisterSimulatorServiceServer(s *grpc.Server, srv SimulatorServiceServer) {
	s.RegisterService(&_SimulatorService_serviceDesc, srv)
}

func _SimulatorService_SetupSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).SetupSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.test.simulation.SimulatorService/SetupSimulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).SetupSimulation(ctx, req.(*SimulationLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_TearDownSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).TearDownSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.test.simulation.SimulatorService/TearDownSimulation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).TearDownSimulation(ctx, req.(*SimulationLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_SetupSimulator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).SetupSimulator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.test.simulation.SimulatorService/SetupSimulator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).SetupSimulator(ctx, req.(*SimulationLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_TearDownSimulator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).TearDownSimulator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/onos.test.simulation.SimulatorService/TearDownSimulator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).TearDownSimulator(ctx, req.(*SimulationLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_Simulate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SimulateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulatorServiceServer).Simulate(m, &simulatorServiceSimulateServer{stream})
}

type SimulatorService_SimulateServer interface {
	Send(*SimulateResponse) error
	grpc.ServerStream
}

type simulatorServiceSimulateServer struct {
	grpc.ServerStream
}

func (x *simulatorServiceSimulateServer) Send(m *SimulateResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SimulatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "onos.test.simulation.SimulatorService",
	HandlerType: (*SimulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetupSimulation",
			Handler:    _SimulatorService_SetupSimulation_Handler,
		},
		{
			MethodName: "TearDownSimulation",
			Handler:    _SimulatorService_TearDownSimulation_Handler,
		},
		{
			MethodName: "SetupSimulator",
			Handler:    _SimulatorService_SetupSimulator_Handler,
		},
		{
			MethodName: "TearDownSimulator",
			Handler:    _SimulatorService_TearDownSimulator_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Simulate",
			Handler:       _SimulatorService_Simulate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "simulation/simulation.proto",
}

func (m *SimulationLifecycleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimulationLifecycleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SimulationLifecycleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Args) > 0 {
		for k := range m.Args {
			v := m.Args[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintSimulation(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintSimulation(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintSimulation(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Simulation) > 0 {
		i -= len(m.Simulation)
		copy(dAtA[i:], m.Simulation)
		i = encodeVarintSimulation(dAtA, i, uint64(len(m.Simulation)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SimulationLifecycleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimulationLifecycleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SimulationLifecycleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *SimulateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimulateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SimulateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintSimulation(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Simulation) > 0 {
		i -= len(m.Simulation)
		copy(dAtA[i:], m.Simulation)
		i = encodeVarintSimulation(dAtA, i, uint64(len(m.Simulation)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SimulateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimulateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SimulateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = encodeVarintSimulation(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0x12
	}
	if m.Trace != nil {
		{
			size, err := m.Trace.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSimulation(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSimulation(dAtA []byte, offset int, v uint64) int {
	offset -= sovSimulation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SimulationLifecycleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Simulation)
	if l > 0 {
		n += 1 + l + sovSimulation(uint64(l))
	}
	if len(m.Args) > 0 {
		for k, v := range m.Args {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovSimulation(uint64(len(k))) + 1 + len(v) + sovSimulation(uint64(len(v)))
			n += mapEntrySize + 1 + sovSimulation(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *SimulationLifecycleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *SimulateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Simulation)
	if l > 0 {
		n += 1 + l + sovSimulation(uint64(l))
	}
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovSimulation(uint64(l))
	}
	return n
}

func (m *SimulateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Trace != nil {
		l = m.Trace.Size()
		n += 1 + l + sovSimulation(uint64(l))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovSimulation(uint64(l))
	}
	return n
}

func sovSimulation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSimulation(x uint64) (n int) {
	return sovSimulation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SimulationLifecycleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSimulation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimulationLifecycleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimulationLifecycleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Simulation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSimulation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSimulation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSimulation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Simulation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSimulation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSimulation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSimulation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Args == nil {
				m.Args = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSimulation
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSimulation
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthSimulation
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthSimulation
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSimulation
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthSimulation
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthSimulation
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSimulation(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthSimulation
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Args[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSimulation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSimulation
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSimulation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimulationLifecycleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSimulation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimulationLifecycleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimulationLifecycleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSimulation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSimulation
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSimulation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimulateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSimulation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimulateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimulateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Simulation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSimulation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSimulation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSimulation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Simulation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSimulation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSimulation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSimulation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSimulation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSimulation
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSimulation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimulateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSimulation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimulateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimulateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trace", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSimulation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSimulation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSimulation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Trace == nil {
				m.Trace = &model.Trace{}
			}
			if err := m.Trace.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSimulation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSimulation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSimulation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSimulation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSimulation
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthSimulation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSimulation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSimulation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSimulation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSimulation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSimulation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSimulation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSimulation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSimulation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSimulation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSimulation = fmt.Errorf("proto: unexpected end of group")
)
