// Code generated by onit-generate. DO NOT EDIT.

package v2alpha1

import (
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
)

type Client interface {
	CronJobsClient
}

func NewClient(resources resource.Client, filter resource.Filter) Client {
	return &client{
		Client:         resources,
		CronJobsClient: NewCronJobsClient(resources, filter),
	}
}

type client struct {
	resource.Client
	CronJobsClient
}
