// Code generated by onit-generate. DO NOT EDIT.

package {{ .Package.Name }}

import (
    {{- range $name, $group := .Groups }}
    {{ $group.Package.Alias }} {{ $group.Package.Path | quote }}
    {{- end }}
    "github.com/onosproject/onos-test/pkg/helm/api/resource"
)

type {{ .Types.Interface }} interface {
    resource.Client
    {{- range $name, $group := .Groups }}
    {{ $group.Names.Proper }}() {{ $group.Package.Alias }}.{{ $group.Types.Interface }}
    {{- end }}
}

func New{{ .Types.Interface }}(resources resource.Client, filter resource.Filter) {{ .Types.Interface }} {
	return &{{ .Types.Struct }}{
		Client: resources,
		filter: filter,
	}
}

type {{ .Types.Struct }} struct {
	resource.Client
	filter resource.Filter
}

{{- range $name, $group := .Groups }}
func (c *{{ .Types.Struct }}) {{ $group.Names.Proper }}() {{ $group.Package.Alias }}.{{ $group.Types.Interface }} {
    return {{ $group.Package.Alias }}.New{{ $group.Types.Interface }}(c.Client, c.filter)
}
{{ end }}
