// Code generated by onit-generate. DO NOT EDIT.

package {{ .Package.Name }}

import (
    {{- range $name, $version := .Versions }}
    {{ $version.Package.Alias }} {{ $version.Package.Path | quote }}
    {{- end }}
    "github.com/onosproject/onos-test/pkg/helm/api/resource"
)

type {{ .Types.Interface }} interface {
    {{- range $name, $version := .Versions }}
    {{ $version.Names.Proper }}() {{ $version.Package.Alias }}.{{ $version.Types.Interface }}
    {{- end }}
}

func New{{ .Types.Interface }}(resources resource.Client, filter resource.Filter) {{ .Types.Interface }} {
	return &{{ .Types.Struct }}{
		Client: resources,
		filter: filter,
	}
}

type {{ .Types.Struct }} struct {
	resource.Client
	filter resource.Filter
}

{{ $group := . }}
{{- range $name, $version := .Versions }}
func (c *{{ $group.Types.Struct }}) {{ $version.Names.Proper }}() {{ $version.Package.Alias }}.{{ $version.Types.Interface }} {
	return {{ $version.Package.Alias }}.New{{ $version.Types.Interface }}(c.Client, c.filter)
}
{{ end }}
