// Code generated by onit-generate. DO NOT EDIT.

package core

import (
	corev1 "github.com/onosproject/onos-test/pkg/helm/api/core/v1"
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
)

type Client interface {
	V1() corev1.Client
}

func NewClient(resources resource.Client, filter resource.Filter) Client {
	return &client{
		Client: resources,
		filter: filter,
	}
}

type client struct {
	resource.Client
	filter resource.Filter
}

func (c *client) V1() corev1.Client {
	return corev1.NewClient(c.Client, c.filter)
}
