// Code generated by onit-generate. DO NOT EDIT.

package v1

import (
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
)

type ServicesClient interface {
	Services() ServicesReader
}

func NewServicesClient(resources resource.Client, filter resource.Filter) ServicesClient {
	return &servicesClient{
		Client: resources,
		filter: filter,
	}
}

type servicesClient struct {
	resource.Client
	filter resource.Filter
}

func (c *servicesClient) Services() ServicesReader {
	return NewServicesReader(c.Client, c.filter)
}
