// Code generated by onit-generate. DO NOT EDIT.

package v1

import (
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"time"
)

type DeploymentsReader interface {
	Get(name string) (*Deployment, error)
	List() ([]*Deployment, error)
}

func NewDeploymentsReader(client resource.Client, filter resource.Filter) DeploymentsReader {
	return &deploymentsReader{
		Client: client,
		filter: filter,
	}
}

type deploymentsReader struct {
	resource.Client
	filter resource.Filter
}

func (c *deploymentsReader) Get(name string) (*Deployment, error) {
	deployment := &appsv1.Deployment{}
	err := c.Clientset().
		AppsV1().
		RESTClient().
		Get().
		NamespaceIfScoped(c.Namespace(), DeploymentKind.Scoped).
		Resource(DeploymentResource.Name).
		Name(name).
		VersionedParams(&metav1.ListOptions{}, metav1.ParameterCodec).
		Timeout(time.Minute).
		Do().
		Into(deployment)
	if err != nil {
		return nil, err
	} else {
		ok, err := c.filter(metav1.GroupVersionKind{
			Group:   DeploymentKind.Group,
			Version: DeploymentKind.Version,
			Kind:    DeploymentKind.Kind,
		}, deployment.ObjectMeta)
		if err != nil {
			return nil, err
		} else if !ok {
			return nil, errors.NewNotFound(schema.GroupResource{
				Group:    DeploymentKind.Group,
				Resource: DeploymentResource.Name,
			}, name)
		}
	}
	return NewDeployment(deployment, c.Client), nil
}

func (c *deploymentsReader) List() ([]*Deployment, error) {
	list := &appsv1.DeploymentList{}
	err := c.Clientset().
		AppsV1().
		RESTClient().
		Get().
		NamespaceIfScoped(c.Namespace(), DeploymentKind.Scoped).
		Resource(DeploymentResource.Name).
		VersionedParams(&metav1.ListOptions{}, metav1.ParameterCodec).
		Timeout(time.Minute).
		Do().
		Into(list)
	if err != nil {
		return nil, err
	}

	results := make([]*Deployment, 0, len(list.Items))
	for _, deployment := range list.Items {
		ok, err := c.filter(metav1.GroupVersionKind{
			Group:   DeploymentKind.Group,
			Version: DeploymentKind.Version,
			Kind:    DeploymentKind.Kind,
		}, deployment.ObjectMeta)
		if err != nil {
			return nil, err
		} else if ok {
			copy := deployment
			results = append(results, NewDeployment(&copy, c.Client))
		}
	}
	return results, nil
}
