// Code generated by onit-generate. DO NOT EDIT.

package v1

import (
	corev1 "github.com/onosproject/onos-test/pkg/helm/api/core/v1"
	"github.com/onosproject/onos-test/pkg/helm/api/resource"
	appsv1 "k8s.io/api/apps/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"time"
)

var ReplicaSetKind = resource.Kind{
	Group:   "apps",
	Version: "v1",
	Kind:    "ReplicaSet",
	Scoped:  true,
}

var ReplicaSetResource = resource.Type{
	Kind: ReplicaSetKind,
	Name: "replicasets",
}

func NewReplicaSet(replicaSet *appsv1.ReplicaSet, client resource.Client) *ReplicaSet {
	return &ReplicaSet{
		Resource:      resource.NewResource(replicaSet.ObjectMeta, ReplicaSetKind, client),
		Object:        replicaSet,
		PodsReference: corev1.NewPodsReference(client, resource.NewUIDFilter(replicaSet.UID)),
	}
}

type ReplicaSet struct {
	*resource.Resource
	Object *appsv1.ReplicaSet
	corev1.PodsReference
}

func (r *ReplicaSet) Delete() error {
	return r.Clientset().
		AppsV1().
		RESTClient().
		Delete().
		NamespaceIfScoped(r.Namespace, ReplicaSetKind.Scoped).
		Resource(ReplicaSetResource.Name).
		Name(r.Name).
		VersionedParams(&metav1.DeleteOptions{}, metav1.ParameterCodec).
		Timeout(time.Minute).
		Do().
		Error()
}
